### PR TITLE
Resolve issue #67, 

### PR DESCRIPTION
**Pull request by oterrier**
add an optionnal parameter callbacks to the train methods of Sequence/Classifier

### CODE REVIEW

**Comment by lfoppiano** [comment]
@oterrier I've seen few more changes than just the new parameter for the callback. Are them included on purpose? 

See my comments in the changes

**Comment by lfoppiano** [comment]
OK. Sorry I was confused at the beginning as I saw some changes back, but this is just because you used a (right now) older version. 

Anyway I see that there are also some small changes in the evaluation, is that correct? Just to be sure I'm understanding correctly ;-)

**Comment by oterrier** [comment]
Hi Luca
My intention was clearly to only introduce changes about callbacks but apparently something went wrong because in the same time Bruno did a PR about the multiprocessing parameter and some changes in the evaluation part.
I'm going to cancel the PR and resubmit it later when my dev environment will be up to date.
Thanks for pointing out the issue
I hope everything is fine with you,still in Japan ?

Best

**Comment by lfoppiano** [comment]
@oterrier no problem. Thanks for sending it again. 

Yes, still in Japan, likely until August next year ;-)

**Pull request closed without merging**
