### PR TITLE
fixed tokenizer invalid escape sequence

### PR DESCRIPTION
**Pull request by de-code**
haven't actually tested it properly. But it contains an invalid escape sequence.

### CODE REVIEW

**Comment by kermitt2** [comment]
The `re.escape` is normally doing the escaping job if not escaped already on the literal string. On the contrary the `r` prefix will produce something invalid:

```
>>> import re
>>> delimiters = "\n\r\t\f\u00A0([ •*,:;?.!/)-−–‐\"“”‘’'\`$]*\u2666\u2665\u2663\u2660\u00A0"
>>> regex = '|'.join(map(re.escape, delimiters))
>>> print(regex)
\
|\	|\
          |\ |\(|\[|\ |\•|\*|\,|\:|\;|\?|\.|\!|\/|\)|\-|\−|\–|\‐|\"|\“|\”|\‘|\’|\'|\\|\`|\$|\]|\*|\♦|\♥|\♣|\♠|\ 
```
 -> is OK

```
>>> delimiters = r"\n\r\t\f\u00A0([ •*,:;?.!/)-−–‐\"“”‘’'\`$]*\u2666\u2665\u2663\u2660\u00A0"
>>> regex = '|'.join(map(re.escape, delimiters))
>>> print(regex)
\\|n|\\|r|\\|t|\\|f|\\|u|0|0|A|0|\(|\[|\ |\•|\*|\,|\:|\;|\?|\.|\!|\/|\)|\-|\−|\–|\‐|\\|\"|\“|\”|\‘|\’|\'|\\|\`|\$|\]|\*|\\|u|2|6|6|6|\\|u|2|6|6|5|\\|u|2|6|6|3|\\|u|2|6|6|0|\\|u|0|0|A|0
>>> regex = '|'.join(delimiters)
>>> print(regex)
\|n|\|r|\|t|\|f|\|u|0|0|A|0|(|[| |•|*|,|:|;|?|.|!|/|)|-|−|–|‐|\|"|“|”|‘|’|'|\|`|$|]|*|\|u|2|6|6|6|\|u|2|6|6|5|\|u|2|6|6|3|\|u|2|6|6|0|\|u|0|0|A|0
```
-> not what we want

**Comment by de-code** [comment]
Okay, admittedly my PR was a bit sloppy and I should have just created an issue. Not sure why in my mind I thought of it being a regular expression.

In any case, Python warnings are useful (displayed for example by default by `pylint` or when running `pytest`). The backslash can only be used with certain characters. And the back-tick is not one of them. The result is that it will add backslash to the list of delimiters, which I assume wasn't intentional (or if it was, the backslash should be escaped).

```bash
$python
>>> import warnings
>>> warnings.resetwarnings()
>>> delimiters = "\n\r\t\f\u00A0([ •*,:;?.!/)-−–‐\"“”‘’'\`$]*\u2666\u2665\u2663\u2660\u00A0"
<stdin>:1: DeprecationWarning: invalid escape sequence \`
>>> delimiters
'\n\r\t\x0c\xa0([ •*,:;?.!/)-−–‐"“”‘’\'\\`$]*♦♥♣♠\xa0'
>>> delimiters = "\n\r\t\f\u00A0([ •*,:;?.!/)-−–‐\"“”‘’'`$]*\u2666\u2665\u2663\u2660\u00A0"
>>> delimiters
'\n\r\t\x0c\xa0([ •*,:;?.!/)-−–‐"“”‘’\'`$]*♦♥♣♠\xa0'
```

**Comment by de-code** [comment]
BTW there is also a warning regarding the comment in `elmo.py`: `$\lambda$`

But I wasn't sure how this is used / rendered. Maybe that should be changed to `$\\lambda$`

**Comment by kermitt2** [comment]
Yes back-tick should not come with the backslash, indeed not intentional, thanks.

**Pull request merged**
