### PR TITLE
Add averages at field level for n-fold eval

### PR DESCRIPTION
**Pull request by kermitt2**
See issue #47

### CODE REVIEW

**Comment by lfoppiano** [comment]
I've tested and looks good.

**Comment by lfoppiano** [comment]
Although I would output the labels in the same order as the as the rest, see an example, the average output month, day, year while everything else output year, month day: 
```
average over 3 folds
            precision    recall  f1-score   support

   <month>     0.9716    0.9661    0.9688        59
     <day>     0.8980    0.9683    0.9314        42
    <year>     0.9948    0.9792    0.9869        64

	macro f1 = 0.9659
	macro precision = 0.9601
	macro recall = 0.9717 


** Worst ** model scores -
                  precision    recall  f1-score   support

          <year>     1.0000    0.9688    0.9841        64
         <month>     0.9655    0.9492    0.9573        59
           <day>     0.8723    0.9762    0.9213        42

all (micro avg.)     0.9521    0.9636    0.9578       165


** Best ** model scores -
                  precision    recall  f1-score   support

          <year>     0.9844    0.9844    0.9844        64
         <month>     0.9667    0.9831    0.9748        59
           <day>     0.9302    0.9524    0.9412        42

all (micro avg.)     0.9641    0.9758    0.9699       165

```

**Comment by kermitt2** [comment]
Ah it's actually more complicated that it sounds! Not sure how to do it :/

**Comment by kermitt2** [comment]
Merging the PR... I open an issue on the sorting of field in the evaluation report...

**Pull request merged**
