### PR TITLE
update imports for fastext - needed when using binary embeddings

### PR DESCRIPTION
**Pull request by lfoppiano**
This PR fixes the imports for fasttext.  

Although the change is minimal, I wonder whether to include fasttext directly in the requirements ([the installation seems to be very brittle, especially on centos, whose ships an older version of GCC](https://github.com/facebookresearch/fastText/issues/1052)) or in the documentation, probably installed from the sources only if needed.. 

Any preference?

### CODE REVIEW

**Comment by kermitt2** [comment]
Hi Luca ! 

The readme points to `fasttextmirror` (0.8.22) which uses `import fastText` (so not a bug with `fasttextmirror`, but the commented import in the requirement files disappeared at some point!). I guess moving to fasttext 0.9.2 instead is better because more recent? 

> I wonder whether to include fasttext directly in the requirements (the installation seems to be very brittle, especially on centos, whose ships an older version of GCC) or in the documentation, probably installed from the sources only if needed..

So we would add (commented) fasttext `0.9.1` in the requirement files because easier to compile than version `0.9.2`?  

I think using the fasttext binary embeddings in general is not a super idea because it slows down everything (no embeddings cache), it was added more for reproducibility purposes. So I would keep it commented/outside the default requirement as before.

**Comment by lfoppiano** [comment]
> Hi Luca !
> 
> The readme points to `fasttextmirror` (0.8.22) which uses `import fastText` (so not a bug with `fasttextmirror`, but the commented import in the requirement files disappeared at some point!). I guess moving to fasttext 0.9.2 instead is better because more recent?

ahh I did not notice that.. fasttextmirror seems not updated since version 0.8.. I guess fasttext 0.9.2 is the most recent. 

> So we would add (commented) fasttext `0.9.1` in the requirement files because easier to compile than version `0.9.2`?

I would go for the version 0.9.2 - but they are needed only if someone uses the bin version of the vectors... 

> I think using the fasttext binary embeddings in general is not a super idea because it slows down everything (no embeddings cache), it was added more for reproducibility purposes. So I would keep it commented/outside the default requirement as before.

The bin offers the advantage to being able to produce embeddings for words not seen before. I've notices a slight improvements certain times. Indeed, the management is inconvenient, more because they are loaded in memory at startup. I guess from the pont of view of the speed after a long startup will not impact the performances..  

I wonder if we could load the vec with the cache and being able to load the from the bin at the same time - looks a bit science fiction

**Comment by kermitt2** [comment]
> The bin offers the advantage to being able to produce embeddings for words not seen before. I've notices a slight improvements certain times. 

Yes it was added to DeLFT (with the help of Pedro!) for this reason. However I observed that, for labeling general texts in English, glove embeddings were always better than the fastext bin, and pmc embeddings always better for scientific text (with random embeddings for unseen words). For text classification, I always got better results with word2vec (.vec) if I remember well. So i think it's only relevant for non-English content?

> I wonder if we could load the vec with the cache and being able to load the from the bin at the same time - looks a bit science fiction

I think it's not that complicated, using the bin library only for unknown tokens, but honestly probably not worth because RNN are outdated by the transformers which are better with small sequences (except when using ELMo maybe, but we have then other problems).

**Comment by lfoppiano** [comment]
Ok, as early spring cleaning, we can forget about this, since the binary does not improve the scoring, it's not portable and is loading the whole blob in memory...

**Comment by kermitt2** [comment]
absolutely !

**Pull request closed without merging**
