### PR TITLE
Add evaluation only command 

### PR DESCRIPTION
**Pull request by lfoppiano**
This PR adds the command `eval` which perform evaluation based on the provided file in `--input`. 

With it I tried to parameterize more the command line. Got inspired from @de-code's [Science beam delft trainer](https://github.com/elifesciences/sciencebeam-trainer-delft)

### CODE REVIEW

**Comment by de-code** [comment]
Thank you for adding this. Just a comment that one thing I found possibly confusing in my implementation, when calling `eval` with `--input`, one might expect that the input is the evaluation data. But it was then doing the train / test split as it would do as part of `train_eval`. i.e. `--input` is still the whole training data.

In the new implementation I can't see the test split. Is it there but I maybe just missed it?
If we don't do the split, `--input` could refer to the evaluation data. But the default, when not specifying the `--input` should probably do the split. Otherwise we would evaluate on the training data? (maybe more specific argument names could help avoid confusion)

n-fold evaluation probably doesn't make sense for this command as we will only have one model?

**Comment by lfoppiano** [comment]
Thanks  @de-code I will have a look at it.

**Comment by de-code** [comment]
Always passing `--input` seems to be sensible.

I think my only quibble is that, `train_eval`, without nfold, would generally evaluate on a different dataset than `eval` would. I think it would be more clear if for `train_eval` we passed in the evaluation dataset separately (I think I already had some exchange regarding that with @kermitt2 but can't find it right now). (If I correctly remember, @kermitt2 's argument was, that the eval dataset during training was there for early stopping)

**Comment by kermitt2** [comment]
I would say (very close to Luca):

- with `eval`, `--input` is mandatory and should be the evaluation data the model is tested against this data (holdout scenario), not having `--input` means no eval data and does not make sense

- with `train_eval`, `--input` gives the whole data to be randomly partitioned into training and eval (with or without nfold), defaulting with the data under `data/sequenceLabelling/grobid/*MODEL_NAME*` (I really don't want to retype the `--input` each time!)

- with `train`, `--input` is the whole data to be used for training defaulting with the data under `data/sequenceLabelling/grobid/*MODEL_NAME*` (see above)

The evaluation dataset is never used for early stop. Either a validation dataset is provided (for example CoNLL2003 NER for reproducibility reason) and used for early stop, or the training dataset will be splitted to use 10% as validation dataset for early stop (which is something transparent).

`train_eval` should apply random split for Grobid stuff, this is the normal scenario (eval set not stable). `train` and `eval` separately corresponds to the holdout eval scenario (eval set stable).

**Comment by de-code** [comment]
There are clearly different use-cases. I think the main issue is that the CLI interface (including my version) is not so clear. It is not intuitive that `train_eval` behaves differently from `train` and `eval`. The `--input` parameter also doesn't give away that much. The description currently says `Provided training file.`.

**Comment by lfoppiano** [comment]
@de-code I tried to improve the description and the documentation. Not sure I managed.

**Pull request merged**
